### PR TITLE
chore: hepmc3-3.2.7

### PR DESCRIPTION
**Pull request by wdconinc**
### Briefly, what does this PR introduce?
Upgrade hepmc3-3.2.7. This will address a vertex attribute bug, i.e. https://gitlab.cern.ch/hepmc/HepMC3/-/merge_requests/279.

### CODE REVIEW

**Comment by wdconinc** [comment]
This has issues due to https://github.com/spack/spack/commit/19c20563cc86140aaf352d72079bd9de292be0ac that I am not sure yet how to resolve. We likely need some way of cherry-picking a commit for certain files only.

**Comment by wdconinc** [comment]
The canonical way of dealing with this is to create a branch on a fork, and only cherry-pick the upstream commits to that branch. That does not make it as manifest which upstream commits are added, and how conflict resolution is applied. There is also no real way to make clean cherry-pick commits within the pull request framework; so it requires direct writes to the branch... Not ideal.

**Comment by wdconinc** [comment]
Cherry-picks for select files are now implemented, so this should now be possible to proceed.

**Comment by wdconinc** [comment]
This will address a vertex attribute bug, i.e. https://gitlab.cern.ch/hepmc/HepMC3/-/merge_requests/279.

**Review by veprbl — APPROVED** [review]

**Pull request merged**
